name: bookwheel-backend

services:
  postgres:
    image: postgres:15.4
    container_name: bookwheel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - bookwheel-postgres-data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./rdb:/rdb
    networks:
      - bookwheel-network
  redis:
    image: redis:7.4.0
    container_name: bookwheel-redis
    ports:
      - '6379:6379'
    networks:
      - bookwheel-network
    volumes:
      - bookwheel-redis-data:/data

volumes:
  bookwheel-postgres-data:
  bookwheel-redis-data:

networks:
  bookwheel-network:
