name: bookwheel-backend

services:
  postgres:
    image: postgres:15.4
    container_name: bookwheel-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - '5432:5432'
    volumes:
      - bookwheel-postgres-data:/var/lib/postgresql/data
    networks:
      - bookwheel-network

volumes:
  bookwheel-postgres-data:

networks:
  bookwheel-network:
